### postgresql
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

### mysql
CREATE TABLE member (
                        id BIGINT AUTO_INCREMENT,
                        name VARCHAR(255),
                        PRIMARY KEY (id)
);


### dml
select * from member;
insert into member (name) values ('abc');
